### ISSUE TITLE
Support for D: installs?

### ISSUE THREAD

**Issue by mhedgpeth** [chef-cookbooks/chef_client_updater#38]
I can't tell by looking at the code, but would this cookbook support upgrading on a D: installation of chef-client? In other words would it preserve the drive on which the chef-client is installed?

**Comment by iennae** [comment]
This won't work right now due to the underlying software used to implement the update. There is no plan at this point to add this feature. This particular request has been declined in the past https://feedback.chef.io/forums/301644-chef-product-feedback/suggestions/8394195-allow-installation-of-chef-server-to-non-standard due to lack of interest from customers/community. You are welcome to add a new request to https://feedback.chef.io/ to start a new conversation on this feature.

**Comment by mhedgpeth** [comment]
Hi @iennae thanks for your quick response to my issue. The chef-client _does_ support `D:` installations; you simply run the MSI with INSTALLLOCATION=D:\opscode in the arguments and it installs just fine.

There are a few issues with it though:

- Every time you run chef-client you have to pass in `-c D:\chef\client.rb`
- There is no way to do a `knife bootstrap` to the `D:` drive
- this cookbook doesn't support it

The third thing is relatively easy to solve; it involves updating the hard-coded value here and the underlying MixLib.install library. I'm not sure how difficult the other parts are.

I'm discussing this with Trevor Hess @ Chef Inc. and am trying to understand either: (1) how to keep the `chef-client` at 200MB or lower, as is stated in the system requirements, or (2) how to get the above features implemented so we can have it on D:, so it won't fill up the OS drive.
