### ISSUE TITLE
When running chef-client as service, service dies after upgrade

### ISSUE THREAD

**Issue by hrak** [chef-cookbooks/chef_client_updater#6]
### Cookbook version
1.0.2

### Chef-client version
upgrade 12.10.24 to 12.19.36

### Platform Details
Ubuntu 16.04 using the chef-client cookbook 7.2.1

### Scenario:
Upgrade without the parent process dying in a forked chef run

### Steps to Reproduce:
use the chef-client cookbook to define a chef-client service that runs chef-client as a daemon (`chef-client::service`).
set `node['chef_client_updater']['version'] to a higher version to trigger upgrade
Send SIGUSR1 to chef-client daemon process to trigger run

### Expected Result:
Upgrade client without daemon process dying

### Actual Result:
chef-client will be upgraded, and the daemon process will die. Chef client service on all nodes will stop running and needs to be manually restarted.

**Comment by mattlqx** [comment]
Yeah, I can't get around this in testing. Same scenario, Ubuntu 16.04 chef-client running in service mode from the `chef-client` cookbook. This cookbook will kill the service and systemd doesn't restart it by default.

Is it vital that the run end as soon as chef-client gets upgraded? Will unexpected things happen if it doesn't? If not, a `post_install_action` of `restart_service` seems like it would work rather than killing the run immediately. I tried to just set `exec_command` and `exec_args` to trigger a service restart but the resource forbids that when chef-client is long-running. :(

**Comment by mattlqx** [comment]
The pull above allows for a `chef-client` attribute to set the chef-client service restart value to "always". With that change, this cookbook then works as desired for package upgrades with systemd.

**Comment by tas50** [comment]
I've added a note in the readme regarding how kill works with chef running as a service. I've also released an updated version of the chef-client cookbook (8.1.1) that sets the restart action in systemd to always, which will start things back up after the upgrade kills chef. Give that a try and let me know if you're still having problems.
